name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 安装 OpenJDK 17
      - name: Install OpenJDK 17
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.9%2B9/OpenJDK17U-jdk_aarch64_linux_hotspot_17.0.9_9.tar.gz
          sudo mkdir -p /usr/lib/jvm
          sudo tar -xzf OpenJDK17U-jdk_aarch64_linux_hotspot_17.0.9_9.tar.gz -C /usr/lib/jvm
          export JAVA_HOME=/usr/lib/jvm/jdk-17+*
          export PATH=$JAVA_HOME/bin:$PATH
          java -version

      # Step 3: 安装 Android NDK r27
      - name: Install Android NDK r27
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip -d $HOME/android-ndk
          export ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r27c
          export PATH=$ANDROID_NDK_HOME:$PATH
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME"

      # Step 4: 设置 Go 环境
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      # Step 5: 安装 Go Mobile 并初始化
      - name: Install Go Mobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          export ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r27c
          gomobile init

      # Step 6: 构建 APK
      - name: Build APK
        run: |
           export ANDROID_NDK_HOME=$HOME/android-ndk/android-ndk-r27c
           go mod tidy
           gomobile build -v -target=android -androidapi 34 -o ble_keyboard.apk

      # Step 7: 上传 APK 到 GitHub Actions 的 artifacts
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ble_keyboard
          path: ble_keyboard.apk
